# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/service_container.html
parameters:
#    parameter_name: value

services:
#    service_name:
#        class: AppBundle\Directory\ClassName
#        arguments: ["@another_service_name", "plain_value", "%parameter_name%"]

    app.service.utils.slug:
            class: AppBundle\Service\Utils\SlugService

    app.service.handler.actorhandler:
            class: AppBundle\Service\Handler\Actorhandler
            arguments: ["@doctrine", "@app.service.utils.upload"]

    app.service.handler.formhandler:
        class: AppBundle\Service\Handler\Formhandler
        arguments: ["@doctrine" ]

    app.service.handler.moviehandler:
        class: AppBundle\Service\Handler\Moviehandler
        arguments: ["@doctrine", "@app.service.utils.upload", "@mailer", "%email_admin%"]

    app.service.utils.upload:
        class: AppBundle\Service\Utils\UploadUtils
        arguments: ["@app.service.utils.string", "%upload_dir%" ]

    app.service.utils.string:
        class: AppBundle\Service\Utils\StringUtils

    app.service.subscriber.movieformsubscriber:
            class: AppBundle\Service\Subscriber\MovieFormSubscriber
            arguments: [  ]
            tags:
                - { name: kernel.event_subscriber } #subscripteur

    app.service.listener.category:
            class: AppBundle\Service\Listener\CategoryListener
            arguments: [ "@app.service.utils.slug" ]
            tags:
                - { name: doctrine.orm.entity_listener}

    app.service.listener.movie:
            class: AppBundle\Service\Listener\MovieListener
            arguments: [ "@app.service.utils.slug", "%upload_dir%" ]
            tags:
                - { name: doctrine.orm.entity_listener}

    app.service.listener.actor:
            class: AppBundle\Service\Listener\ActorListener
            arguments: [ "@doctrine", "@app.service.utils.slug", "%upload_dir%" ]
            tags:
                - { name: doctrine.orm.entity_listener}

    app.service.form.selectform:
            class: AppBundle\Form\MovieSearchType
            arguments: ["@doctrine" ]
            tags:
                - { name: form.type }

    app.service.twig.allmoviesservice:
                class: AppBundle\Service\Twig\AllMoviesService
                arguments: ["@doctrine" ]

